apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-dashboard.fullname" . }}
  labels:
    {{- include "sentinel-dashboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "sentinel-dashboard.selectorLabels" . | nindent 4 }}
